### ISSUE TITLE
Just completed but it already completed earlier.

### ISSUE THREAD

**Issue by WillPoulson** [bevry/taskgroup#26]
Hi, I keep getting this error

> The task [x➞  task 2 for [y]] just completed, but it had already completed earlier, this is unexpected.

I's happening as I'm calling the same task twice however I'm creating it as a new task each time. I'd just like to check that this should be happening and isn't an issue with the library.

If it is a feature could we please have it changed to a warning level log as it's currently being caught as an error by my error handler.

**Comment by WillPoulson** [comment]
Nevermind I found the argument `errorOnExcessCompletions`.

**Comment by balupton** [comment]
What is your code here? This error should only occur if you have completed the same task instantiation twice.
